### ISSUE TITLE
terraform.plan.txt not being populated

### ISSUE THREAD

**Issue by estevaofay** [smsilva/terraform-packager#1]
Hi!

it seems that the output file `terraform.plan.txt` is not being populated!

![image](https://user-images.githubusercontent.com/13035425/147091242-d499a861-5311-43a2-b30a-4dbe86d941b4.png)

This `.txt` could be useful when pasting the terraform plan in a pull request!

I may submit a PR later

**Comment by smsilva** [comment]
Hi Estevão, thanks for raise this.

The default behavior of stackrun script is to create three empty files for binary (.plan), JSON and text file (.txt).

This is made only to avoid the Terraform Container to create those files as root user.

May I can create a default command named `plan-txt` or `plan-no-color` to enable this behavior?

The main idea is to keep the primary plan output with the colors by default.

If you need to do this before the change, you can accomplish that passing the Terraform command as the example below

```bash
plan -no-color -out /opt/output/terraform.plan | tee /opt/output/terraform.plan.txt
```
